ARG ARG_DOCKER_TAG=latest

FROM planolport/gdal_oracle:$ARG_DOCKER_TAG

LABEL maintainer="PlanolPort<planolport@portdebarcelona.cat>"

ARG CUSTOM_UID=65535
ARG USER_NAME=appuser
ARG base_path=/home/${USER_NAME}

RUN getent passwd ${USER_NAME} || useradd --create-home -u ${CUSTOM_UID} ${USER_NAME}

ENV PATH_DEVELOPER_MODE=/project
ENV PATH_BASE_PACKAGES=${PATH_DEVELOPER_MODE}

USER root

RUN mkdir ${PATH_DEVELOPER_MODE} && \
    chown -R $USER_NAME:root ${PATH_DEVELOPER_MODE} && \
    chmod -R u=rwx,g=rwx,o=rx ${PATH_DEVELOPER_MODE}

WORKDIR ${PATH_DEVELOPER_MODE}

COPY --chown=$USER_NAME:root ./requirements.txt ./requirements.txt

ENV USER_NAME=${USER_NAME}
USER $USER_NAME

RUN python -m venv --system-site-packages /home/$USER_NAME/venv \
    && . /home/$USER_NAME/venv/bin/activate

# Add local bin for $USER_NAME to PATH (for future pip installed scripts)
ENV PATH=/home/$USER_NAME/venv/bin:$PATH

RUN  pip install --upgrade pip -r requirements.txt --no-cache-dir

COPY --chown=$USER_NAME:root apb_extra_utils_pckg/ ./apb_extra_utils_pckg/
RUN pip install  --config-setting editable_mode=compat --no-build-isolation --editable apb_extra_utils_pckg --no-cache-dir

COPY --chown=$USER_NAME:root ./apb_extra_osgeo_utils_pckg/ ./apb_extra_osgeo_utils_pckg/
RUN pip install  --config-setting editable_mode=compat --no-build-isolation --editable apb_extra_osgeo_utils_pckg --no-cache-dir

COPY --chown=$USER_NAME:root ./apb_spatial_utils_pckg/ ./apb_spatial_utils_pckg/
RUN pip install  --config-setting editable_mode=compat --no-build-isolation --editable apb_spatial_utils_pckg --no-cache-dir

COPY --chown=$USER_NAME:root ./apb_cx_oracle_spatial_pckg/ ./apb_cx_oracle_spatial_pckg/
# Set env var for package python apb_cx_oracle_spatial
ENV PATH_INSTANT_CLIENT_ORACLE=$ORACLE_HOME
RUN pip install  --config-setting editable_mode=compat --no-build-isolation --editable apb_cx_oracle_spatial_pckg --no-cache-dir

COPY --chown=$USER_NAME:root apb_pandas_utils_pckg/ ./apb_pandas_utils_pckg/
RUN pip install  --config-setting editable_mode=compat --no-build-isolation --editable apb_pandas_utils_pckg --no-cache-dir

COPY --chown=$USER_NAME:root ./apb_duckdb_utils_pckg/ ./apb_duckdb_utils_pckg/
RUN pip install  --config-setting editable_mode=compat --no-build-isolation --editable apb_duckdb_utils_pckg --no-cache-dir
# Set extra extensions perinstalled on duckdb
RUN python -c  \
    "import duckdb; \
    duckdb.install_extension('sqlite'); \
    duckdb.install_extension('spatial'); \
    duckdb.install_extension('json'); \
    duckdb.install_extension('httpfs')"

CMD ["python"]
