name: python_packages_DEV
channels:
- defaults
- conda-forge
- anaconda
- javascript
dependencies:
- python >=3.7,<4
- nodejs <13
- conda-forge::gdal >=3,<4
- conda-forge::geopandas >=0.8,<0.9
- cx_Oracle <9
- pip >=20
- pip:
#   - --requirement file:requirements.txt
