name: python_packages_DEV
channels:
- conda-forge
- defaults
- anaconda
- javascript
dependencies:
- python
- nodejs=10.13
- conda-forge::gdal=3.5
- conda-forge::geopandas=0.8
- ipython
- cython
- pip
