name: python_packages
channels:
- conda-forge
- defaults
- anaconda
- javascript
dependencies:
- python=3.9
- nodejs=10.13
- conda-forge::gdal=3.5
- conda-forge::geopandas=0.8
- ipython
- cython
- pip