alter user GIS identified by GIS123;

grant CREATE SESSION, ALTER SESSION, CREATE DATABASE LINK, CREATE MATERIALIZED VIEW, CREATE PROCEDURE,
    CREATE PUBLIC SYNONYM, CREATE ROLE, CREATE SEQUENCE, CREATE SYNONYM, CREATE TABLE, CREATE TRIGGER,
    CREATE TYPE, CREATE VIEW, CREATE ANY INDEX, UNLIMITED TABLESPACE to GIS;
